const getMap = () => { //Hardcoded as explained in the README
  return {
    BACLARAN: {EDSA_TAFT: 0.58},
    EDSA_TAFT: {BACLARAN: 0.58, DJOSE_RECTO: 7.80, ARANETA_CUBAO: 12.6},
    DJOSE_RECTO: {EDSA_TAFT: 7.80, ARANETA_CUBAO: 8.16, ROOSEVELT: 9.65},
    ROOSEVELT: {DJOSE_RECTO: 9.65, NORTHAVE: 2},
    ARANETA_CUBAO: {EDSA_TAFT: 12.60, DJOSE_RECTO: 8.16, NORTHAVE: 4.1, LRT2SANTOLAN: 4.35},
    NORTHAVE: {ROOSEVELT: 2, ARANETA_CUBAO: 4.1},
    LRT2SANTOLAN: {ARANETA_CUBAO: 4.35}
  };
};
export default getMap;
